apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-lab
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/registry-nfs/overlays/lab
    repoURL: 'https://github.com/hornjason/argocd-lab.git'
    targetRevision: demo
  project: default
  syncPolicy:
    automated: {}
