apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: migrate-registry-dev
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://api.managed.foo.bar:6443'
  source:
    path: manifests/migrate-registry/overlays/dev
    repoURL: 'https://github.com/hornjason/argocd-lab.git'
    targetRevision: demo
  project: default
  syncPolicy:
    automated: {}
