apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
   logging: 2
   managementState: Managed
   replicas: 2
   storage:
     pvc:
       claim: image-registry-pvc
